### ISSUE TITLE
Build fails on Vercel sporadically

### ISSUE THREAD

**Issue by IGassmann** [blitz-js/next-superjson-plugin#25] opened 2022-09-08 09:44 UTC
### Describe the bug

Next.js build fails on Vercel sporadically with many errors looking as such:

```
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/vercel/path0/pages/auth/login.tsx")'

Caused by:
  0: Failed to create plugin instance
  1: missing requires CPU features: "EnumSet(AVX512DQ | AVX512VL | AVX512F)"', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.212.1/src/plugin.rs:222:14
```

### Expected behavior

The build should always run successfully.

### Version

0.4.0

### Config

```javascript
{
  experimental: {
    esmExternals: "loose",
    swcPlugins: [
      [
        "next-superjson-plugin",
        {
          excluded: [],
        },
      ],
    ],
  },
  webpack: (config, context) => {
    config.resolve.fallback = { fs: false }

    return config
  },
}
```

### Additional context

Next.js version: `12.2.5`

I believe this error happens when the host machine that is building the project on Vercel has a CPU that doesn’t have either of those features: AVX-512DQ, AVX-512VL, or AVX-512F. Since Vercel might use different host machines for each build, this would explain why it would fail sporadically.

**Comment by orionmiz** [comment] 2022-09-09 03:16
Could you please try to build with a new release? (v0.4.1)

**Comment by IGassmann** [comment] 2022-09-13 10:27
@orionmiz, unfortunately, the issue is still persisting with the new release.

**Comment by orionmiz** [comment] 2022-09-14 03:44
Might be fixed with #29 + Next.js canary

But doesn't ensure since I can't reproduce this bug in local machine.

**Comment by orionmiz** [comment] 2022-09-16 20:03
@IGassmann Plugin v0.4.2 is just released.

Could you give it another try with Next.js v12.3.1?

It will be a challenging issue if it is not fixed by the update.

**Comment by cellulosa** [comment] 2022-09-17 16:45
heya I managed to upgrade using `npm install --legacy-peer-deps` (#31).

I still get a panic error:

    thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/node_modules/next/dist/client/dev/amp-dev.js")'

    Caused by:
        0: failed to invoke `/node_modules/next-superjson-plugin/next_superjson.wasm` as js transform plugin at /node_modules/next-superjson-plugin/next_superjson.wasm
        1: RuntimeError: out of bounds memory access
               at <unnamed> (<module>[329]:0x62a25)
               at <unnamed> (<module>[355]:0x6bd6b)
               at <unnamed> (<module>[357]:0x6d15e)
               at <unnamed> (<module>[41]:0xc3fb)
               at <unnamed> (<module>[105]:0x1cf8d)
               at <unnamed> (<module>[158]:0x343b0)
               at <unnamed> (<module>[183]:0x3c8ce)
               at <unnamed> (<module>[124]:0x2332b)
               at <unnamed> (<module>[751]:0xd2250)
               at <unnamed> (<module>[750]:0xd1fe1)
               at <unnamed> (<module>[589]:0xaf798)
        2: heap_get_oob', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.224.0/src/plugin.rs:216:14
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    [1]    31891 bus error  npm run dev

**Comment by IGassmann** [comment] 2022-09-22 12:25
It's fixed with v0.4.2 and Next.js v12.3.1.

**Comment by martinbianchi** [comment] 2022-09-22 15:08
This just happened to me with v0.4.2 and Next.js v12.3.1

**Comment by IGassmann** [comment] 2022-10-05 08:06
@martinbianchi @orionmiz, I confirm that this is actually still happening.

**Comment by sluukkonen** [comment] 2022-10-05 10:28
I'm also seeing this on a local CI machine that has an `Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz` CPU. 

Using Next 12.3.1 and next-superjson-plugin 0.4.2.

**Comment by IGassmann** [comment] 2022-10-11 06:19
@orionmiz I'm confident this happens due to the build cache of Vercel. Vercel maintains a build cache between builds but doesn't always use the same CPU between every build. So `next-superjson-plugin` can be once compiled for a specific CPU, and then the same compiled output would be used by another CPU on a subsequent build due to the build cache. If I rebuild the deployment without the cache on Vercel, the build is always successful.

The solution here might be to replicate `@next/swc` build and publish process, which seems to have solved this problem. The package seems to pre-compile binaries with [NAPI-RS](https://napi.rs/). Check out their [GitHub Workflow](https://github.com/vercel/next.js/blob/canary/.github/workflows/build_test_deploy.yml) and the [package configuration](https://github.com/vercel/next.js/tree/canary/packages/next-swc).

**Comment by orionmiz** [comment] 2022-10-11 12:43
@IGassmann You really found a breakthrough.
This issue is delivered to Vercel through SWC maintainer.
They will look at it and make solutions.
Thanks!

----

**UPDATE:**
Heard from the SWC Team, that it might not be a problem from the build cache.
So I've decided to find a solution from the plugin itself.

The problem is that some SIMD instructions (like AVX-512) cannot be run in the unsupported CPUs.
But the compiler gets them into the plugin without considering the client which runs it.

Our goal is to find how to compile the plugin depending on the client's hardware (or just deopt all the kind of SIMD)
Then I found [a useful target feature](https://github.com/WebAssembly/relaxed-simd/blob/main/proposals/relaxed-simd/Overview.md) introducing local non-deterministic SIMD supported by LLVM.
Fortunately, there was a way to apply it to the plugin easily with RUSTFLAGS.

So the plugin [v0.4.3](https://github.com/blitz-js/next-superjson-plugin/releases/tag/v0.4.3) including that feature is just released now.
Would you mind testing the build on Vercel with v0.4.3?

**Comment by IGassmann** [comment] 2022-10-12 08:07
Thanks! We've merged the fix. I'll let you know if the issue still happens.

BTW, I would recommend adding a new comment to this issue for any new updates instead of editing your existing comment. Otherwise, people that are subscribed to this issue (including me) don't get notified about it.

**Comment by orionmiz** [comment] 2022-10-12 08:52
> Thanks! We've merged the fix. I'll let you know if the issue still happens.
> 
> BTW, I would recommend adding a new comment to this issue for any new updates instead of editing your existing comment. Otherwise, people that are subscribed to this issue (including me) don't get notified about it.

@IGassmann Oops, I've thought you would get notification from just mentioning PR.

Anyway, if this error is still existing after updating to v0.4.3,
Providing minimal reproduction of the project would be a important clue to resolve this issue.
Because I've tried to reproduce this error by deploying [this project](https://github.com/orionmiz/next-superjson-plugin-vercel-error-repro) (It also checks CPU so that make me notice the changes of build environment) several times, but couldn't make it.
Maybe the source code could be one of the causes.

**Comment by IGassmann** [comment] 2022-10-12 11:06
@orionmiz it's difficult to reproduce because it only happens occasionally. Plus, we're on the enterprise plan of Vercel, which might use different machines to build the project than projects on the standard plan.

**Comment by orionmiz** [comment] 2022-10-12 11:52
@IGassmann That makes sense. Hope the update to get rid of this issue.

**Comment by IGassmann** [comment] 2022-10-12 14:58
The issue is still occurring with `v0.4.3`.

Let's recap what we know:
- The build occasionally fails on Vercel
- If we rebuild the failed deployment on Vercel (with or without the build cache), it won't fail.
- The build always fails on a machine with the `Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz` CPU, according to @sluukkonen. [That CPU doesn't have the AVX-512 extension](https://www.techpowerup.com/cpu-specs/xeon-e5-2673-v3.c2884).
- The error message says that there are some missing required CPU features. Either AVX512DQ, AVX512VL, or AVX512F. Those are all implementations of the CPU AVX-512 extension.
- The error is [thrown by Wasmer](https://rustdoc.swc.rs/src/wasmer/sys/instance.rs.html#63).
- This plugin is compiled on GitHub Actions for the target `wasm32-unknown-unknown`

The `CpuFeature` error type is thrown when the module was compiled with a CPU feature that is not available on the current host that is running the module.

This makes me think that the GitHub Action environment has those CPU features available, which makes the compiled output expect them as well. The solution might be to either find a way to compile the plugin without those CPU features or to compile it in an environment that doesn't have those CPU features.

Here's a related issue: https://github.com/wasmerio/wasmer/issues/2707

**Comment by sluukkonen** [comment] 2022-10-12 19:07
In our case, the bug manifests when trying to build our Next app on a custom Github Actions runners that have that older Xeon. We only see it occasionally, since most of our runners have newer processors that do support the relevant AVX 512 instructions.  The job also shares `node_modules` between machines via the Github Actions cache.

**Comment by IGassmann** [comment] 2022-10-13 06:34
@sluukkonen would be able to build on the older Xeon runner without the cache and report back if it also fails, please?

**Comment by orionmiz** [comment] 2022-10-15 11:12
**SWC update has arrived from our request:**
- https://github.com/swc-project/swc/pull/6163

Plugin has been updated already:
- #43 

Wait for the coming Next.js canary release to use resolved plugin runner.

**Comment by orionmiz** [comment] 2022-10-18 21:51
Next.js [v12.3.2-canary.30](https://github.com/vercel/next.js/releases/tag/v12.3.2-canary.30) including SWC update is just released!

Please follow these steps and let's make sure the error has gone:
1. Update Next.js to the canary
2. Update Plugin to the v0.4.8
3. Build without wasm cache

**Closed as completed** 2022-10-26 05:14 UTC
Labels: bug
