### ISSUE TITLE
Cannot start the app 

### ISSUE THREAD

**Issue by rawnly** [blitz-js/next-superjson-plugin#74] opened 2023-03-15 00:54 UTC
### Verify Next.js canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Describe the bug

![CleanShot 2023-03-15 at 01 48 07](https://user-images.githubusercontent.com/16429579/225174909-c598f045-abbb-4928-878e-3062acd02c11.gif)

### Expected behavior

I'd like to run the app	

### Reproduction link
[repository](https://github.com/Rawnly/next-superjson-repo)
[codesandbox link](https://codesandbox.io/p/github/Rawnly/next-superjson-repo/main?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253A%2522clf8yys0n000lg1ge48xc6lek%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clf8yyto500153b6iz8nspfv3%2522%253A%257B%2522key%2522%253A%2522clf8yyto500153b6iz8nspfv3%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522key%2522%253A%2522clf8yyto500163b6is3k6vit2%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clf8yz4sc00ax3b6ii2nee5a2%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clf8yz2wt006j3b6iw2vy0syo%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clf8yyto500153b6iz8nspfv3%2522%252C%2522spacesOrder%2522%253A%255B%2522clf8yyto500153b6iz8nspfv3%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)

### Version

13.2.5-canary.3

### Config

```javascript
/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    appDir: true,
    swcPlugins: [["next-superjson-plugin", { debug: true }]],
  },
};

module.exports = nextConfig;
```

**Comment by hect1c** [comment] 2023-03-15 11:45
This also happens with NextJS version `13.2.5-canary.4` I had to revert back to the following versions to get this working

- next `13.1.6`
- next-superjson-plugin `0.4.9`

**Comment by RealGatt** [comment] 2023-03-16 07:48
Can also replicate. Causes a segmentation fault issue when building.

**Comment by darthmaim** [comment] 2023-03-17 08:42
This is the related issue in the next.js repo: vercel/next.js#46989. It's not just this plugin.

**Comment by mauriceackel** [comment] 2023-03-18 20:49
I ran into the same issue today. I got it working with:
- next `13.2.3`
- next-superjson-plugin `0.5.6`

I had to clear my `.next` folder to get it working after downgrading my NextJS version

**Comment by elie222** [comment] 2023-03-18 22:03
Same issue here. Commenting out the use of the plugin till resolved.

**Comment by orionmiz** [comment] 2023-03-19 08:11
This appears to be an issue from the recent turbopack update (vercel/next.js#46971)
There is nothing we can do on the plugin side, so please use a version of Next.js lower than 13.2.4 until the issue is resolved.

**Comment by kevin-courbet** [comment] 2023-03-20 11:51
Even after pinning 13.2.3 and 0.5.6 (rm node_modules .next), I am still getting an error, albeit a different one. The dev server will start, but as soon as there is a render, I'll get this. 

```
failed to invoke `.../node_modules/.pnpm/next-superjson-plugin@0.5.6_bybiisvvvxj62fig2dzdxxp2ea/node_modules/next-superjson-plugin/dist/next_superjson.wasm` as js transform plugin at .../node_modules/.pnpm/next-superjson-plugin@0.5.6_bybiisvvvxj62fig2dzdxxp2ea/node_modules/next-superjson-plugin/dist/next_superjson.wasm
    1: RuntimeError: unreachable
    2: unreachable', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.245.27/src/plugin.rs:228thread '<unnamed><unnamed>' panicked at ':14' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some(".../src/app/layout.tsx")'
```

In the past 2 days I have tried various combinations of versions, going back to previous working commits (by deleting node_modules / .next), to no avail. Really puzzling... 

For the time being, I just rolled out a quick and dirty serialization / deserialization utility /shrug.

**Comment by ericwang401** [comment] 2023-04-01 03:47
A workaround is to downgrade to next@13.2.0 and delete the `.next` folder and run your dev server. I was running next@13.2.4 and downgraded to that version and it worked.

**Comment by mrbaguettefr** [comment] 2023-04-12 08:24
I got it working: 
- Downgraded to next@13.2.3
`    "next": "13.2.3",` in package.json
- Run `npm install`
- Deleted the .next folder
- (Re)Started the dev server

**Comment by darthmaim** [comment] 2023-04-18 09:41
The upstream issue in next.js was fixed in the latest canary, but plugins now need to update to the latest swc version.

**Closed as completed** 2023-04-21 14:58 UTC
Labels: bug

**Comment by orionmiz** [comment] 2023-04-21 15:13
It's been a long wait, everyone.

Please try next-superjson-plugin v0.5.7 with next canary.

**Comment by arnaudriegert** [comment] 2023-04-21 15:36
Thank you @orionmiz 

It works for me with next@13.3.1-canary.17 (not 13.3.0)

Also noteworthy that it _seems_ I can serialize dates without the plugin on that canary version.

**Comment by arashi-dev** [comment] 2023-04-22 12:06
next@13.3.1 is out now :)
no need canary version anymore

**Comment by Ashutsoh1729** [comment] 2023-06-21 14:34
Hello,
I am facing the error where i have used next@13.3.1 and next-superjson-plugin v 0.5.7 but it shows error

Here Is the error 

error - ./node_modules/next/dist/client/dev/amp-dev.js
Error: failed to process failed to invoke plugin: failed to invoke plugin on 'Some("/Users/ashutoshhota/Coding/web development/Next JS/Ongoing Projects/Messenger Clone/Messenger Clone/Messenger-Clone/node_modules/next/dist/client/dev/amp-dev.js")'

Caused by:
    0: failed to invoke `/Users/ashutoshhota/Coding/web development/Next JS/Ongoing Projects/Messenger Clone/Messenger Clone/Messenger-Clone/node_modules/next-superjson-plugin/dist/next_superjson.wasm` as js transform plugin at /Users/ashutoshhota/Coding/web development/Next JS/Ongoing Projects/Messenger Clone/Messenger Clone/Messenger-Clone/node_modules/next-superjson-plugin/dist/next_superjson.wasm
    1: RuntimeError: unreachable
    2: unreachable

Please help

**Comment by orionmiz** [comment] 2023-06-23 17:02
@Ashutsoh1729 Please update Next.js and plugin

**Comment by Ashutsoh1729** [comment] 2023-06-23 18:41
Thank you @orionmiz

I have now updated both to their latest versions and it worked. Thank you again.

**Comment by sneko** [comment] 2024-02-14 16:42
I was having the same issue while using Next.js `v14.1.0`, my solution was to downgrade both `next-superjson-plugin` and so `superjson` (since using it directly) to have `superson` `v1` used.

Here my package.json:
```
    "next-superjson-plugin": "0.5.10",
    "next": "14.1.0",
    "superjson": "^1.13.3",
```

**Comment by michaeltrinh7** [comment] 2024-04-03 18:44
It works. Thank you [sneko](https://github.com/sneko)
